### ISSUE TITLE
品牌搜索时没找到xiaomi miot auto

### ISSUE THREAD

**Issue by dreamfly999** [wangrui1573/Xiaoai_PlayLocal#2]
品牌搜索时没找到xiaomi miot auto
![image](https://github.com/wangrui1573/Xiaoai_PlayLocal/assets/34122505/f8bae3f6-3cc7-49fe-bc7c-1c2521f726b2)
是不是点开上面的Xiaomi后红框中的这个
![image](https://github.com/wangrui1573/Xiaoai_PlayLocal/assets/34122505/ba87d2cc-65ba-4045-a2e8-d8ade79b92c0)

**Comment by wangrui1573** [comment]
是从HACS中添加的吗？
![image](https://github.com/wangrui1573/Xiaoai_PlayLocal/assets/42831156/60c33d7a-be73-4d3b-8db8-cfcdc9529f39)
